CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS statuses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tickets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    priority TEXT CHECK(priority IN ('Low','Medium','High')),
    authorId INTEGER,
    statusId INTEGER,
    FOREIGN KEY(authorId) REFERENCES users(id),
    FOREIGN KEY(statusId) REFERENCES statuses(id)
);

CREATE TABLE IF NOT EXISTS ticket_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticketId INTEGER NOT NULL,
    userId INTEGER NOT NULL,
    text TEXT NOT NULL,

    FOREIGN KEY(ticketId) REFERENCES tickets(id) ON DELETE CASCADE,
    FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE
);